// Generated by CoffeeScript 1.6.3
require('DOM');

require('Utilities');

window.FacebookLikeObserver = (function() {
  function FacebookLikeObserver() {}

  FacebookLikeObserver.prototype.getIntegrationPatterns = function() {
    return [".UFILikeLink", ".UFICommentActions > a", ".UFILikeThumb"];
  };

  FacebookLikeObserver.prototype.getEventType = function() {
    return "click";
  };

  FacebookLikeObserver.prototype.getID = function(obj) {
    var attachments, classes, content, photoContainerImage, snowliftContainerImage;
    classes = {
      ".UFIComment": ".UFICommentBody",
      ".photoUfiContainer": ".hasCaption",
      ".uiStreamStory": ".userContent",
      ".storyContent": ".userContent",
      ".article": ".shareSubtext",
      ".timelineUnitContainer": ".userContent"
    };
    content = DOM.findRelative(obj, classes);
    if (Utilities.stripTags(content)) {
      content = Utilities.stripTags(content);
    }
    if (content === "error") {
      attachments = obj.closest("div[role=article]").find(".uiStreamAttachments");
      if (attachments.length > 0) {
        content = attachments.find("img").attr("src");
      }
      snowliftContainerImage = obj.closest(".fbPhotoSnowliftContainer").find(".spotlight");
      if (snowliftContainerImage.length > 0) {
        content = snowliftContainerImage.attr("src");
      }
      photoContainerImage = obj.closest(".fbxPhoto").find(".fbPhotoImage");
      if (photoContainerImage.length > 0) {
        content = photoContainerImage.attr("src");
      }
    } else {
      content = content.substr(0, Constants.getContentLength());
    }
    return content;
  };

  FacebookLikeObserver.prototype.getMetaData = function(obj) {
    var contentArea, currentProfileName, currentUserName, fieldContent, interactionType, interactionTypes, location, objectOwner, objectOwnerClasses, storyType, timelineCapsule;
    interactionTypes = {
      'like': 'like',
      'unlike': 'unlike',
      'gefällt mir': 'like',
      'gefällt mir nicht mehr': 'unlike'
    };
    fieldContent = Utilities.stripTags(obj.html()).toLowerCase();
    interactionType = interactionTypes[fieldContent];
    if (!interactionType) {
      interactionType = "unknown/like/unlike";
    }
    objectOwnerClasses = {
      '.UFIComment': 'a.UFICommentActorName',
      'div[role=article]': '.actorName a',
      '.photoUfiContainer': '.fbPhotoContributorName a',
      'div[role=article] .uiStreamMessage': 'a:nth-child(2)',
      '.timelineUnitContainer': '.fwb',
      '.storyContent': '.passiveName'
    };
    objectOwner = Utilities.stripTags(DOM.findRelative(obj, objectOwnerClasses));
    location = "unknown";
    currentProfileName = $("#fbProfileCover ._8_2").html();
    currentUserName = $(".headerTinymanName").html();
    timelineCapsule = obj.closest('.fbTimelineCapsule');
    contentArea = obj.closest('#contentArea');
    if (timelineCapsule.length > 0) {
      location = "profile";
    }
    if (currentProfileName === currentUserName) {
      location += "self";
    }
    if (contentArea.length > 0) {
      location = "newsfeed";
    }
    storyType = FacebookUtilities.getStoryType(obj);
    return {
      "interaction_type": interactionType,
      "object_owner": Utilities.hash(objectOwner),
      "object_type": storyType,
      "location": location
    };
  };

  return FacebookLikeObserver;

})();
