// Generated by CoffeeScript 1.6.3
this.FacebookUtilities = (function() {
  function FacebookUtilities() {}

  FacebookUtilities.getUserID = function() {
    debugger;
    return Utilities.hash($("#mainContainer").first("a").value());
  };

  FacebookUtilities.getStoryType = function(obj) {
    var className, storyClasses;
    storyClasses = {
      '.UFIComment': 'comment',
      'div[role=article]': 'status',
      '.photoUfiContainer': 'photo',
      '.timelineUnitContainer': 'status'
    };
    for (className in storyClasses) {
      if ($(className).find(obj).length > 0) {
        return storyClasses[className];
      }
    }
    return "unknown";
  };

  return FacebookUtilities;

})();
